name: Android CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test-ibrahim-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check commit message body for "ibrahim"
        run: |
          MESSAGE_BODY=$(git log -1 --pretty=format:"%b" ${{ github.event.pull_request.head.sha }})

          if echo "$MESSAGE_BODY" | grep -q "ibrahim"; then
            echo "Commit message body contains ibrahim"
          else
            echo "Commit message body does not contain ibrahim"
            exit 1
          fi
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Unit Tests
        run: ./gradlew test   
