name: Android CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test-ibrahim-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check commit message for "ibrahim"
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)

          if [[ $COMMIT_MESSAGE == *"ibrahim"* ]]; then
            echo "Commit message contains 'ibrahim'"
          else
            echo "Commit message does not contain 'ibrahim'"
            exit 1
          fi

      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
