name: AppCompat Lint Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Check for AppCompat issues
        run: ./gradlew lint

      - name: Comment on pull request
        uses: unsplash/comment-on-pr@v1
        with:
          message: |
            The following AppCompat issues were found:
            ${{ steps.lint.outputs.stdout }}
        if: ${{ steps.lint.outputs.stdout != '' }}