name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 23
        target: default
        arch: x86
        profile: Nexus 6

    - name: Run unit tests
      run: ./gradlew test
