name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86
        profile: pixel
        script: |
          echo no | avdmanager create avd --force --name test --abi $ABI --package "system-images;android-$API_LEVEL;$TAG" --device "pixel"
          emulator -avd test -no-window -no-audio -no-boot-anim -no-accel -memory 2048 &
          android-wait-for-emulator

    - name: Build and run tests
      run: ./gradlew connectedAndroidTest --stacktrace
