name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 28
          arch: x86
          profile: Nexus 5X
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none
          emulator-build: 7425822
          script: echo "Generated AVD snapshot for caching."

    - name: Build and run tests
      run: ./gradlew connectedAndroidTest --stacktrace
