name: Workflow Caller

on:
  workflow_run:
    workflows:
      - "Android CI"
    branches:
      - master

jobs:
  trigger_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Unit Test
        uses: actions/github-script@v4
        with:
          script: |
            const token = "${{ secrets.GITHUB_TOKEN }}";
            const octokit = new Octokit({ auth: token });
            const { data: { id } } = await octokit.actions.createWorkflowDispatch({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.repository }}",
              workflow_id: "unit-test.yml"
            });
